# General settings
name: 'custom'      # Warning: 'debug' and 'test' are reserved name that have a special behavior
wandb: 'offline'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: /home/nico/projects/SparseDiffArchitecture/outputs/2025-11-08/10-26-00-custom/checkpoints/custom/last.ckpt          # Use absolute path
test_variance: 1
generated_path: null    # path of generated samples, this file should be of pickle type

check_val_every_n_epochs: 10
sample_every_val: 10
val_check_interval: null
samples_to_generate: 10       # We advise to set it to 2 x batch_size maximum
samples_to_save: 10
chains_to_save: 10
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 10
final_model_samples_to_save: 10
final_model_chains_to_save: 10

evaluate_all_checkpoints: False

# sampling parameters
skip: 1
pdm_enabled: True                         # enforce PDM constraints during sampling
project_only_last_step: True             # if False, project at each sampling step
# resampling_per_step: 1                    # number of sample + projection iterations per diffusion step
max_weight: 22                            # sum of all edge weights per graph must be below this value
four_neighborhood: True                   # if True, only 4-neighborhood edges are allowed, others will be removed during projection
