# Training settings
n_epochs: 10000
batch_size: 64
lr: 0.0002
clip_grad: null          # float, null to disable
save_model: True
num_workers: 16
progress_bar: true
weight_decay: 1e-12
optimizer: adamw
seed: 0
